name 'cluster-demo'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cluster-demo'
long_description 'Installs/Configures cluster-demo'
version '0.1.0'
depends 'apt'
